// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {project} from '../models';
import {artifacts} from '../models';
import {search} from '../models';

export function ActivityCounts():Promise<main.ActivityCounts>;

export function BrowseTree():Promise<Array<main.BrowseRow>>;

export function DeleteProject(arg1:string,arg2:boolean):Promise<project.Deleted>;

export function FacetCounts():Promise<main.FacetCountsResult>;

export function FeaturesByRepo():Promise<Array<main.FeatureRow>>;

export function GetArtifact(arg1:string):Promise<artifacts.Artifact>;

export function GetArtifactBody(arg1:string):Promise<string>;

export function GetLiveBody(arg1:string):Promise<string>;

export function GetPref(arg1:string):Promise<string>;

export function ListArtifacts(arg1:artifacts.ListFilter,arg2:string,arg3:number,arg4:string,arg5:string):Promise<Array<artifacts.Artifact>>;

export function ListSessions(arg1:main.SessionFilter,arg2:number):Promise<Array<search.Hit>>;

export function LiveMtime():Promise<number>;

export function ProjectHeatmap(arg1:number,arg2:number):Promise<Array<main.HeatmapCell>>;

export function ProjectSparkline(arg1:string,arg2:number):Promise<Array<main.SparklinePoint>>;

export function ReadFile(arg1:string):Promise<string>;

export function RecentFiles(arg1:string,arg2:number):Promise<Array<main.FileActivity>>;

export function RecentRepos(arg1:number):Promise<Array<main.RepoActivity>>;

export function SearchFTS(arg1:search.Params):Promise<Array<search.Hit>>;

export function SearchHybrid(arg1:string,arg2:artifacts.ListFilter,arg3:number,arg4:string,arg5:string):Promise<Array<search.HybridResult>>;

export function SearchToolUses(arg1:main.ToolUseFilter):Promise<Array<main.ToolUseHit>>;

export function SessionFacets():Promise<main.SessionFacetCounts>;

export function SessionPathByID(arg1:string):Promise<string>;

export function SetPref(arg1:string,arg2:string):Promise<void>;

export function Version():Promise<string>;
