// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {artifacts} from '../models';
import {search} from '../models';

export function FacetCounts():Promise<main.FacetCountsResult>;

export function FeaturesByRepo():Promise<Array<main.FeatureRow>>;

export function GetArtifact(arg1:string):Promise<artifacts.Artifact>;

export function GetArtifactBody(arg1:string):Promise<string>;

export function ListArtifacts(arg1:artifacts.ListFilter,arg2:string,arg3:number):Promise<Array<artifacts.Artifact>>;

export function ListSessions(arg1:main.SessionFilter,arg2:number):Promise<Array<search.Hit>>;

export function LiveMtime():Promise<number>;

export function ReadFile(arg1:string):Promise<string>;

export function SearchFTS(arg1:search.Params):Promise<Array<search.Hit>>;

export function SearchHybrid(arg1:string,arg2:artifacts.ListFilter,arg3:number):Promise<Array<search.HybridResult>>;

export function SearchToolUses(arg1:main.ToolUseFilter):Promise<Array<main.ToolUseHit>>;

export function SessionFacets():Promise<main.SessionFacetCounts>;
