// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FacetCounts() {
  return window['go']['main']['App']['FacetCounts']();
}

export function ListArtifacts(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListArtifacts'](arg1, arg2, arg3);
}

export function SearchFTS(arg1) {
  return window['go']['main']['App']['SearchFTS'](arg1);
}

export function SearchHybrid(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchHybrid'](arg1, arg2, arg3);
}
