// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FacetCounts() {
  return window['go']['main']['App']['FacetCounts']();
}

export function FeaturesByRepo() {
  return window['go']['main']['App']['FeaturesByRepo']();
}

export function GetArtifact(arg1) {
  return window['go']['main']['App']['GetArtifact'](arg1);
}

export function GetArtifactBody(arg1) {
  return window['go']['main']['App']['GetArtifactBody'](arg1);
}

export function ListArtifacts(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListArtifacts'](arg1, arg2, arg3);
}

export function ListSessions(arg1, arg2) {
  return window['go']['main']['App']['ListSessions'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function SearchFTS(arg1) {
  return window['go']['main']['App']['SearchFTS'](arg1);
}

export function SearchHybrid(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchHybrid'](arg1, arg2, arg3);
}

export function SessionFacets() {
  return window['go']['main']['App']['SessionFacets']();
}
