// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ActivityCounts() {
  return window['go']['main']['App']['ActivityCounts']();
}

export function FacetCounts() {
  return window['go']['main']['App']['FacetCounts']();
}

export function FeaturesByRepo() {
  return window['go']['main']['App']['FeaturesByRepo']();
}

export function GetArtifact(arg1) {
  return window['go']['main']['App']['GetArtifact'](arg1);
}

export function GetArtifactBody(arg1) {
  return window['go']['main']['App']['GetArtifactBody'](arg1);
}

export function GetPref(arg1) {
  return window['go']['main']['App']['GetPref'](arg1);
}

export function ListArtifacts(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListArtifacts'](arg1, arg2, arg3);
}

export function ListSessions(arg1, arg2) {
  return window['go']['main']['App']['ListSessions'](arg1, arg2);
}

export function LiveMtime() {
  return window['go']['main']['App']['LiveMtime']();
}

export function ProjectHeatmap(arg1, arg2) {
  return window['go']['main']['App']['ProjectHeatmap'](arg1, arg2);
}

export function ProjectSparkline(arg1, arg2) {
  return window['go']['main']['App']['ProjectSparkline'](arg1, arg2);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function RecentFiles(arg1, arg2) {
  return window['go']['main']['App']['RecentFiles'](arg1, arg2);
}

export function RecentRepos(arg1) {
  return window['go']['main']['App']['RecentRepos'](arg1);
}

export function SearchFTS(arg1) {
  return window['go']['main']['App']['SearchFTS'](arg1);
}

export function SearchHybrid(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchHybrid'](arg1, arg2, arg3);
}

export function SearchToolUses(arg1) {
  return window['go']['main']['App']['SearchToolUses'](arg1);
}

export function SessionFacets() {
  return window['go']['main']['App']['SessionFacets']();
}

export function SetPref(arg1, arg2) {
  return window['go']['main']['App']['SetPref'](arg1, arg2);
}
